### ISSUE TITLE
too many bugs are there in this cms

### ISSUE THREAD

**Issue by is1and** [martinzhou2015/SRCMS#6]
change password

**Comment by martinzhou2015** [comment]
Hi, 
Thank you so much for your report. Would you please submit details about these bugs? That's because, only in this way can we confirm and fix them. 

Also, we would like to invite you to join our development team to make SRCMS a better content management system. To contact with us, you could send mails to 1009465756@qq.com or send messages via QQ( Number:1009465756 ).

Hope we could hear from you soon!

Yours,
Martin
